### ISSUE TITLE
Breaking change in 0.9.9 from 0.9.8

### ISSUE THREAD

**Issue by pagameba** [guard/rb-inotify#68]
https://github.com/guard/rb-inotify/commit/528f86a44d7198a44ed2245b59de324e8a819855#diff-ba0ad9930c92f66b00543bcb9a88fbb6R20 added a breaking change by requiring ruby >= 2.0.0 so now installing compass (which requires rb-inotify >= 0.9) fails when it didn't an hour ago.

**Comment by guncha** [comment]
Same here. Have you people heard of semver?

**Comment by owengalenjones** [comment]
Same here.

**Comment by junaruga** [comment]
This change's affection can happen `sass/sass` Ruby 1.8, 1.9 test on Travis.

https://github.com/junaruga/sass
https://travis-ci.org/sass/sass/branches

**Comment by matthewd** [comment]
@guncha the SemVer definition explicitly states this is a valid change: 

http://semver.org/#what-should-i-do-if-i-update-my-own-dependencies-without-changing-the-public-api

**Comment by guncha** [comment]
@matthewd, you are, of course, technically correct (the best kind of correct). In spirit, though, if a patch level update breaks the build, which this did for anyone on Ruby 1.9, I'll consider that a semver violation.

**Comment by ioquatix** [comment]
So, this is my fault, I accept 100% responsibility for this, since I deliberately added that (as I typically add for all gems). I've not tested this gem with 1.9 and actually, didn't imagine anyone was still using 1.9 in any meaningful way, since it's well past end of life.

@guncha It's not a semantic versioning violation, so framing it like that isn't helping. Especially that other gems depending on rb-inotify 0.x releases should be pinning the version to a specific release IMHO.

I have to admit, this gem is in a very bad state. The biggest issue is that there were never any unit tests, so I've been struggling to test it, by installing it, and then running the `listen` test suite to see if everything works. It's a pain and I don't have 1.8 and 1.9 installed to test.

I only recently took over maintaining it since it had outstanding PRs, some for years, most of which I've either rejected or merged, so we've made some progress. But the next step is to add some tests. Perhaps someone can assist with that.

My opinion is that it's reasonable to support `Ruby >= 2.0` for the 1.0 release, and 0.99 was the rc to ensure that the (minor) recent changes haven't broken anything major. However, if there are still a significant number of users on Ruby 1.8 and 1.9, now is the time to figure out if this gem, in it's final 1.0 release, should support them or not.

They are welcome to continue using the 0.9.8 release which will continue working for the foreseeable future. However, by releasing 1.0 with support for 1.8 and 1.9, we would probably need to support 1.8 and 1.9 into the future.

Thoughts?

**Comment by ioquatix** [comment]
So, one other option which I think is reasonable, given the work that @junaruga has done in the PR to add travis testing for 1.8 and 1.9, is to implement the following process:

- Revert the version limit, and test on 1.8 and 1.9 - release a 1.0 from this code base.
- Re-assert the Ruby >= 2.0 limit, and release a 2.0 version. All future work done on this branch.

I think this is ultimately a bit more messy, but it at least supports existing users more gracefully, with the caveat that they won't get future updates on the 2.x branch unless someone works to back-port them and test them.

**Comment by junaruga** [comment]
First of all, I know your situation for maintaining. Thank you for maintaining this package.
I encourage you.

> My opinion is that it's reasonable to support Ruby >= 2.0 for the 1.0 release, and 0.99 was the rc to ensure that the (minor) recent changes haven't broken anything major. However, if there are still a significant number of users on Ruby 1.8 and 1.9, now is the time to figure out if this gem, in it's final 1.0 release, should support them or not.

I agree with your opinion.
- `rb-inotify` 0.x supports Ruby 1.8 and 1.9.
- `rb-inotify` 1.x does not support Ruby 1.8 and 1.9.

As a reference, `sass`'s next minor version dump does not support Ruby 1.8 and 1.9.

To develop 1.x version maintaining 0.x version,  creating `0-x-stable` branch may be good idea.

Ref: See below package's repositories are using the way.
https://github.com/socketry/nio4r
https://github.com/rails/rails

**Comment by ioquatix** [comment]
Okay, @junaruga let's roll with your idea. It's a good one.

**Comment by junaruga** [comment]
I like to reopen this ticket until next 0.x version bump.
I like you to close this ticket after next 0.x version bump.

**Comment by ioquatix** [comment]
It got closed automatically when I merged the PR.

**Comment by junaruga** [comment]
It may be because of my comment on the PR. Sorry.

**Comment by Sylor73** [comment]
When will there be a patch?

**Comment by matthewd** [comment]
It's worth noting that a modern build environment (e.g., a sufficiently recent version of Bundler) will deal with this situation correctly, and not try to use an incompatible version of a gem.

**Comment by ioquatix** [comment]
@matthewd I appreciate your positivity. I wonder if the versions of bundler that still work on 1.8 and 1.9 do this or not?

@Sylor73 @pagameba do you mind explaining exactly your use case that lead to the failure? How did you try to install/update? Were you just installing gems using `gem install` or did you use `bundler` and if so how did it fail?

**Comment by ioquatix** [comment]
@junaruga Are we good to release 0-x-stable as 0.9.10?

**Comment by junaruga** [comment]
@ioquatix Yes I am fine for that!

**Comment by deivid-rodriguez** [comment]
> @matthewd I appreciate your positivity. I wonder if the versions of bundler that still work on 1.8 and 1.9 do this or not?

@ioquatix I think even the most recent bundler version still supports 1.8 and 1.9! :)

**Comment by junaruga** [comment]
@ioquatix Bundler supports Ruby 1.8 and 1.9 too.
Ref: https://github.com/bundler/bundler/blob/master/.travis.yml

**Comment by ioquatix** [comment]
Well, I'm blown away that bundler, with the most recent version, still supports 1.8 and 1.9 - that's crazy amazing!

**Comment by ioquatix** [comment]
Okay, 0.9.10 has been released from 0-x-stable branch. This is the last release to support Ruby 1.8 and 1.9 - any future development/releases will be on the 1.x family and will no longer support 1.8 or 1.9

**Comment by pagameba** [comment]
@ioquatix my use case - we have a web site that still requires ubuntu 12.04 because of a PHP 5.3 dependency (in the process of updating but that's another story), part of the tool chain is to use compass which relies on rb-inotify >= 0.9.   I solved the problem for my team by installing rb-inotify=0.9.8 before installing compass.

**Comment by ioquatix** [comment]
@pagameba Do you use a Gemfile? Can you pin to a specific version of rb-inotify? Is this isn't the only gem you are having issues with given the age of your platform?

**Comment by pagameba** [comment]
@ioquatix no, I have a Dockerfile for building a docker image for CI but we still use chef for deploying to AWS instances (again, that's in transition).  In both cases, we just `gem install compass`.  As mentioned, `gem install -v 0.9.8 rb-inotify` before installing compass fixes the problem for us.  Its a hopefully short term problem as we are in the final stages of upgrading the entire stack to newer stuff, just a slog getting it all done and tested :)
